language: go
go:
    - tip
    - 1.6
    - 1.5
install:
    - go get github.com/issue9/assert
    - go get github.com/issue9/term/colors
    - go get github.com/issue9/utils
    - go get github.com/issue9/version
    - go get github.com/issue9/is
    - go get golang.org/x/text/language
    - go get golang.org/x/text/message
